export { yura, YuraApp, formatStats, FrameRing, eases } from './app'
export type { EaseFn, EaseName, Ease, MotionTimingOptions, GameSetup, InteractiveOptions } from './app'
export type { YuraOptions, YuraStats } from './app'
export { shapes, galaxy, sphere, ring, vortex, flow, box, cone, helix, text, image } from './shapes'
export type { ShapeSpec } from './shapes'
export { looks, cinematic, cyberpunk, aurora, neon, studio, sakura } from './looks'
export type { LookName } from './looks'
export { presetNames, resolvePreset } from './presets'
export type { PresetConfig } from './presets'
export { YuraScene, SceneObject, SceneInput } from './scene'
export type { SceneOptions, AddOptions, ShapeName, TextHandle } from './scene'
export { materials, matte, plastic, metal, neon as neonMaterial, resolveMaterial } from './materials'
export type { MaterialLike } from './materials'
export { YuraError, CODES } from '@yura/core'
export type { Backend, Vec3 } from '@yura/core'
export type { LookParams, MotionParams, SceneMaterial, AttractorParams, BlendMode, ToneMapping } from '@yura/renderer-webgpu'
export { MAX_ATTRACTORS, DEFAULT_ATTRACTOR_RADIUS } from '@yura/renderer-webgpu'
export { FxPool, FxTrailEmitter, FX_FLOATS } from './fx'
export type { BurstOptions, TrailOptions, CelebrateOptions, FxRandom } from './fx'
export type { TrailHandle } from './scene'
export { yuraLayer, YuraThreeLayer, composeSwarmCamera, glProjectionToWebGPU, fovAspectFromProjection, eyeFromView, worldPositionOf, YURA_SHAPE_RADIUS } from './three'
export type { YuraLayerOptions, ThreeCameraLike, ThreeRendererLike, ThreeObject3DLike, Mat4Like } from './three'
export { gameAudio, clamp01, pickupTone, jumpTone, landTone, winTones, noteToFreq } from './audio'
export type { LoopOpts, LoopHandle } from './audio'
export type { GameAudio, ToneSpec, ToneWave } from './audio'
export { lyrics, orderLines, buildTimeline, timelineDuration, wrapTime, advanceCursor } from './lyrics'
export type { LyricLine, LyricInput, LyricsOptions, LyricsRun, LyricEvent } from './lyrics'
export { sweepProgress, applySweepDirection } from './app'
export type { MorphNowOptions, SweepDirection } from './app'
export { segmentGraphemes, charCoord, layoutLines, layoutColumns } from './shapes'
export type { ColumnPlacement } from './shapes'
export type { TextOptions, TextAlign, LinePlacement } from './shapes'
export { kineticLyrics, planKinetic, framePoses, phaseAt, originAt, poseToStyle, kineticDuration, DEFAULT_BPM } from './kinetic'
export type { KineticLine, KineticInput, KineticPlanOptions, KineticOptions, KineticRun, KineticScheduler, KineticElement, PlannedLine, GlyphStyle } from './kinetic'
export { motions, kineticMoods, kineticCatalog, identityPose, composePose, glyphRank, glyphProgress, hash01, SCRAMBLE_GLYPHS, ACCENT_ENTERS, ACCENT_HOLD } from './motions'
export type { GlyphPose, MotionGlyph, GlyphOrder, TransitionRecipe, HoldRecipe, LayoutRecipe, MotionPhase, MotionEntry, KineticMood, KineticMoodName, EnterName, HoldName, ExitName, LayoutName } from './motions'
export { lyricStage, planStage, lyricSpanOf, activeLine, transitionState, schemeVars, fitScale, defineLyricStage, readLyricNodes, stageOptionsFromAttributes } from './stage'
export type { StageOptions, StagePlanOptions, StagePlan, StageCut, StageRun, StageDocument } from './stage'
export { stageThemes, FONT_STACKS } from './stage-themes'
export type { StageTheme, StageThemeName, StageScheme, StageTexture, StageFonts, WorldName, DecorName, CameraName, TransitionName } from './stage-themes'
export { cameraMoves, cameraAt, stageTransitions, transitionAt, shakeAt, accentFlash, grainOffset, beatPhase, beatPulse, beatSeconds, CAMERA_DISTANCE, CAMERA_FOV, FLASH_MAX, TRANSITION_SECONDS, DEFAULT_STAGE_BPM } from './stage-motion'
export type { CameraPose, TransitionFrame } from './stage-motion'
export { stageDecor, decorMarkup, decorLive, formatTimecode, escapeHtml, TIMECODE_FPS } from './stage-decor'
export type { DecorContext, DecorLiveFrame } from './stage-decor'
export { stageWorlds, createStageWorld, monolithLayout, shardLayout, dustLayout, petalLayout, petalAt, glyphStarLayout, tunnelRingZ, PETAL_SPAN, TUNNEL_SPACING, TUNNEL_RINGS } from './stage-world'
export type { ThreeNamespace, StageWorld, WorldFrame, WorldOptions, Placement } from './stage-world'
export { yuraSite, splitElement, YURA_HEAD_SNIPPET } from './site'
export type { SiteOptions, SiteRun, SiteWindow } from './site'
export { splitText, textRevealStyles, blockReveals, blockRevealAt, viewProgress, pinProgress, parallaxShift, marqueeStep, countAt, magneticOffset, follow, loaderAt, LOADER_LIFT_SECONDS } from './site-motion'
export type { SplitToken, BlockFrame, BlockRevealName, LoaderFrame } from './site-motion'
