export { WebGPUParticleRenderer } from './renderer'
export type { LookParams, MotionParams, RendererOptions, ExternalCamera } from './renderer'
export { WebGPUModelRenderer } from './model-renderer'
export type { SceneMaterial, MeshHandle } from './model-renderer'
export { meshes, sphereMesh, boxMesh, planeMesh, discMesh, torusMesh, cylinderMesh, torusKnotMesh } from './meshes'
export type { MeshGeometry } from './meshes'
export { loadGLB, parseGLB } from './gltf'
export type { GLTFModel, GLTFPrimitive, GLTFMaterial } from './gltf'
export { SIM_WGSL, RENDER_WGSL, POST_WGSL } from './shaders'
export { ENV_WGSL, BLIT_WGSL, PBR_WGSL, FX_WGSL } from './model-shaders'
export * from './blend'
export * from './look-math'
export { curlNoiseSource, turbulenceTermSource, DEFAULT_TURBULENCE, DEFAULT_TURBULENCE_SCALE } from './shaders'
export { attractorTermSource, packAttractors, MAX_ATTRACTORS, ATTRACTOR_VEC4S, ATTRACTOR_RADIUS2_SLOT, ATTRACTOR_ARRAY_VEC4S, DEFAULT_ATTRACTOR_RADIUS, ATTRACTOR_DIST_EPSILON, SIM_PARAMS_BYTES } from './shaders'
export type { AttractorParams } from './shaders'
